In [41]:
url = "postgresql://postgres:Bungie1992!@database-1.cxzzhtb4x7ub.us-east-2.rds.amazonaws.com:5432/postgres"

In [44]:
import pandas as pd

from sqlalchemy import create_engine

engine = create_engine(url)

connect = engine.connect()
query = "select * from crime"

dataframe = pd.read_sql(query, con=connect)
dataframe

,incident_number,highest_offense_description,occurred_date,occurred_time,report_date,report_time,zip_code,census_tract,clearance_date,x_coordinate,y_coordinate,latitude,longitude
0,20213650197,ASSAULT W/INJURY-FAM/DATE VIOL,2021-12-31,436,2021-12-31,436,78736,330,2021-12-31,3066128,3066128,30.23640862,-97.89627861
1,20213650632,ASSAULT W/INJURY-FAM/DATE VIOL,2021-12-31,1223,2021-12-31,1223,78726,346,2021-12-31,3081086,3081086,30.42004712,-97.84416748
2,20213650144,AGG ASLT STRANGLE/SUFFOCATE,2021-12-31,244,2021-12-31,244,78752,433,2021-12-31,3128894,3128894,30.33388619,-97.69480728
3,20213651189,FAMILY DISTURBANCE,2021-12-31,1933,2021-12-31,1933,78702,8,2022-01-01,3119243,3119243,30.27401815,-97.7270251
4,20213650916,TERRORISTIC THREAT,2021-12-31,1621,2021-12-31,1621,78741,23.15,2021-12-31,3118423,3118423,30.23364383,-97.73071195
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43915,20215000094,THEFT,2021-01-01,2030,2021-01-02,116,78758,454,2021-01-06,3118561,3118561,30.40108901,-97.72575381
43916,20215000078,CRIMINAL MISCHIEF,2021-01-01,1300,2021-01-01,1746,78753,439,2021-01-06,3136701,3136701,30.41482764,-97.66781711
43917,202111947,FAMILY DISTURBANCE,2021-01-01,2208,2021-01-01,2208,78702,8,2021-01-08,3126638,3126638,30.26325906,-97.70388535
43918,20215000238,HARASSMENT,2021-01-01,900,2021-01-03,2359,78702,8,2021-01-21,3125478,3125478,30.26402985,-97.70753972
43919,20215000037,THEFT BY SHOPLIFTING,2021-01-01,1012,2021-01-01,1300,78744,24.51,2021-01-01,3102586,3102586,30.1683339,-97.78259876